/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IAccountSignerMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from '@solana/kit';
import { SPL_STAKE_POOL_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const DECREASE_VALIDATOR_STAKE_DISCRIMINATOR = new Uint8Array([
  145, 203, 107, 123, 71, 63, 35, 225,
]);

export function getDecreaseValidatorStakeDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    DECREASE_VALIDATOR_STAKE_DISCRIMINATOR
  );
}

export type DecreaseValidatorStakeInstruction<
  TProgram extends string = typeof SPL_STAKE_POOL_PROGRAM_ADDRESS,
  TAccountStakePool extends string | IAccountMeta<string> = string,
  TAccountStaker extends string | IAccountMeta<string> = string,
  TAccountStakePoolWithdrawAuthority extends
    | string
    | IAccountMeta<string> = string,
  TAccountValidatorList extends string | IAccountMeta<string> = string,
  TAccountValidatorStake extends string | IAccountMeta<string> = string,
  TAccountTransientStake extends string | IAccountMeta<string> = string,
  TAccountClock extends string | IAccountMeta<string> = string,
  TAccountRent extends
    | string
    | IAccountMeta<string> = 'SysvarRent111111111111111111111111111111111',
  TAccountSystemProgram extends
    | string
    | IAccountMeta<string> = '11111111111111111111111111111111',
  TAccountStakeProgram extends string | IAccountMeta<string> = string,
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountStakePool extends string
        ? ReadonlyAccount<TAccountStakePool>
        : TAccountStakePool,
      TAccountStaker extends string
        ? ReadonlySignerAccount<TAccountStaker> &
            IAccountSignerMeta<TAccountStaker>
        : TAccountStaker,
      TAccountStakePoolWithdrawAuthority extends string
        ? ReadonlyAccount<TAccountStakePoolWithdrawAuthority>
        : TAccountStakePoolWithdrawAuthority,
      TAccountValidatorList extends string
        ? WritableAccount<TAccountValidatorList>
        : TAccountValidatorList,
      TAccountValidatorStake extends string
        ? WritableAccount<TAccountValidatorStake>
        : TAccountValidatorStake,
      TAccountTransientStake extends string
        ? WritableAccount<TAccountTransientStake>
        : TAccountTransientStake,
      TAccountClock extends string
        ? ReadonlyAccount<TAccountClock>
        : TAccountClock,
      TAccountRent extends string
        ? ReadonlyAccount<TAccountRent>
        : TAccountRent,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      TAccountStakeProgram extends string
        ? ReadonlyAccount<TAccountStakeProgram>
        : TAccountStakeProgram,
      ...TRemainingAccounts,
    ]
  >;

export type DecreaseValidatorStakeInstructionData = {
  discriminator: ReadonlyUint8Array;
  lamports: bigint;
  transientStakeSeed: bigint;
};

export type DecreaseValidatorStakeInstructionDataArgs = {
  lamports: number | bigint;
  transientStakeSeed: number | bigint;
};

export function getDecreaseValidatorStakeInstructionDataEncoder(): Encoder<DecreaseValidatorStakeInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['lamports', getU64Encoder()],
      ['transientStakeSeed', getU64Encoder()],
    ]),
    (value) => ({
      ...value,
      discriminator: DECREASE_VALIDATOR_STAKE_DISCRIMINATOR,
    })
  );
}

export function getDecreaseValidatorStakeInstructionDataDecoder(): Decoder<DecreaseValidatorStakeInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['lamports', getU64Decoder()],
    ['transientStakeSeed', getU64Decoder()],
  ]);
}

export function getDecreaseValidatorStakeInstructionDataCodec(): Codec<
  DecreaseValidatorStakeInstructionDataArgs,
  DecreaseValidatorStakeInstructionData
> {
  return combineCodec(
    getDecreaseValidatorStakeInstructionDataEncoder(),
    getDecreaseValidatorStakeInstructionDataDecoder()
  );
}

export type DecreaseValidatorStakeInput<
  TAccountStakePool extends string = string,
  TAccountStaker extends string = string,
  TAccountStakePoolWithdrawAuthority extends string = string,
  TAccountValidatorList extends string = string,
  TAccountValidatorStake extends string = string,
  TAccountTransientStake extends string = string,
  TAccountClock extends string = string,
  TAccountRent extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountStakeProgram extends string = string,
> = {
  stakePool: Address<TAccountStakePool>;
  staker: TransactionSigner<TAccountStaker>;
  stakePoolWithdrawAuthority: Address<TAccountStakePoolWithdrawAuthority>;
  validatorList: Address<TAccountValidatorList>;
  validatorStake: Address<TAccountValidatorStake>;
  transientStake: Address<TAccountTransientStake>;
  clock: Address<TAccountClock>;
  rent?: Address<TAccountRent>;
  systemProgram?: Address<TAccountSystemProgram>;
  stakeProgram: Address<TAccountStakeProgram>;
  lamports: DecreaseValidatorStakeInstructionDataArgs['lamports'];
  transientStakeSeed: DecreaseValidatorStakeInstructionDataArgs['transientStakeSeed'];
};

export function getDecreaseValidatorStakeInstruction<
  TAccountStakePool extends string,
  TAccountStaker extends string,
  TAccountStakePoolWithdrawAuthority extends string,
  TAccountValidatorList extends string,
  TAccountValidatorStake extends string,
  TAccountTransientStake extends string,
  TAccountClock extends string,
  TAccountRent extends string,
  TAccountSystemProgram extends string,
  TAccountStakeProgram extends string,
  TProgramAddress extends Address = typeof SPL_STAKE_POOL_PROGRAM_ADDRESS,
>(
  input: DecreaseValidatorStakeInput<
    TAccountStakePool,
    TAccountStaker,
    TAccountStakePoolWithdrawAuthority,
    TAccountValidatorList,
    TAccountValidatorStake,
    TAccountTransientStake,
    TAccountClock,
    TAccountRent,
    TAccountSystemProgram,
    TAccountStakeProgram
  >,
  config?: { programAddress?: TProgramAddress }
): DecreaseValidatorStakeInstruction<
  TProgramAddress,
  TAccountStakePool,
  TAccountStaker,
  TAccountStakePoolWithdrawAuthority,
  TAccountValidatorList,
  TAccountValidatorStake,
  TAccountTransientStake,
  TAccountClock,
  TAccountRent,
  TAccountSystemProgram,
  TAccountStakeProgram
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? SPL_STAKE_POOL_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    stakePool: { value: input.stakePool ?? null, isWritable: false },
    staker: { value: input.staker ?? null, isWritable: false },
    stakePoolWithdrawAuthority: {
      value: input.stakePoolWithdrawAuthority ?? null,
      isWritable: false,
    },
    validatorList: { value: input.validatorList ?? null, isWritable: true },
    validatorStake: { value: input.validatorStake ?? null, isWritable: true },
    transientStake: { value: input.transientStake ?? null, isWritable: true },
    clock: { value: input.clock ?? null, isWritable: false },
    rent: { value: input.rent ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    stakeProgram: { value: input.stakeProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.rent.value) {
    accounts.rent.value =
      'SysvarRent111111111111111111111111111111111' as Address<'SysvarRent111111111111111111111111111111111'>;
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.stakePool),
      getAccountMeta(accounts.staker),
      getAccountMeta(accounts.stakePoolWithdrawAuthority),
      getAccountMeta(accounts.validatorList),
      getAccountMeta(accounts.validatorStake),
      getAccountMeta(accounts.transientStake),
      getAccountMeta(accounts.clock),
      getAccountMeta(accounts.rent),
      getAccountMeta(accounts.systemProgram),
      getAccountMeta(accounts.stakeProgram),
    ],
    programAddress,
    data: getDecreaseValidatorStakeInstructionDataEncoder().encode(
      args as DecreaseValidatorStakeInstructionDataArgs
    ),
  } as DecreaseValidatorStakeInstruction<
    TProgramAddress,
    TAccountStakePool,
    TAccountStaker,
    TAccountStakePoolWithdrawAuthority,
    TAccountValidatorList,
    TAccountValidatorStake,
    TAccountTransientStake,
    TAccountClock,
    TAccountRent,
    TAccountSystemProgram,
    TAccountStakeProgram
  >;

  return instruction;
}

export type ParsedDecreaseValidatorStakeInstruction<
  TProgram extends string = typeof SPL_STAKE_POOL_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    stakePool: TAccountMetas[0];
    staker: TAccountMetas[1];
    stakePoolWithdrawAuthority: TAccountMetas[2];
    validatorList: TAccountMetas[3];
    validatorStake: TAccountMetas[4];
    transientStake: TAccountMetas[5];
    clock: TAccountMetas[6];
    rent: TAccountMetas[7];
    systemProgram: TAccountMetas[8];
    stakeProgram: TAccountMetas[9];
  };
  data: DecreaseValidatorStakeInstructionData;
};

export function parseDecreaseValidatorStakeInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>
): ParsedDecreaseValidatorStakeInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 10) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      stakePool: getNextAccount(),
      staker: getNextAccount(),
      stakePoolWithdrawAuthority: getNextAccount(),
      validatorList: getNextAccount(),
      validatorStake: getNextAccount(),
      transientStake: getNextAccount(),
      clock: getNextAccount(),
      rent: getNextAccount(),
      systemProgram: getNextAccount(),
      stakeProgram: getNextAccount(),
    },
    data: getDecreaseValidatorStakeInstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
