/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IAccountSignerMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from '@solana/kit';
import { SPL_STAKE_POOL_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';
import {
  getFundingTypeDecoder,
  getFundingTypeEncoder,
  type FundingType,
  type FundingTypeArgs,
} from '../types';

export const SET_FUNDING_AUTHORITY_DISCRIMINATOR = new Uint8Array([
  48, 2, 114, 83, 165, 222, 71, 233,
]);

export function getSetFundingAuthorityDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    SET_FUNDING_AUTHORITY_DISCRIMINATOR
  );
}

export type SetFundingAuthorityInstruction<
  TProgram extends string = typeof SPL_STAKE_POOL_PROGRAM_ADDRESS,
  TAccountStakePool extends string | IAccountMeta<string> = string,
  TAccountManager extends string | IAccountMeta<string> = string,
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountStakePool extends string
        ? WritableAccount<TAccountStakePool>
        : TAccountStakePool,
      TAccountManager extends string
        ? ReadonlySignerAccount<TAccountManager> &
            IAccountSignerMeta<TAccountManager>
        : TAccountManager,
      ...TRemainingAccounts,
    ]
  >;

export type SetFundingAuthorityInstructionData = {
  discriminator: ReadonlyUint8Array;
  arg: FundingType;
};

export type SetFundingAuthorityInstructionDataArgs = { arg: FundingTypeArgs };

export function getSetFundingAuthorityInstructionDataEncoder(): Encoder<SetFundingAuthorityInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['arg', getFundingTypeEncoder()],
    ]),
    (value) => ({
      ...value,
      discriminator: SET_FUNDING_AUTHORITY_DISCRIMINATOR,
    })
  );
}

export function getSetFundingAuthorityInstructionDataDecoder(): Decoder<SetFundingAuthorityInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['arg', getFundingTypeDecoder()],
  ]);
}

export function getSetFundingAuthorityInstructionDataCodec(): Codec<
  SetFundingAuthorityInstructionDataArgs,
  SetFundingAuthorityInstructionData
> {
  return combineCodec(
    getSetFundingAuthorityInstructionDataEncoder(),
    getSetFundingAuthorityInstructionDataDecoder()
  );
}

export type SetFundingAuthorityInput<
  TAccountStakePool extends string = string,
  TAccountManager extends string = string,
> = {
  stakePool: Address<TAccountStakePool>;
  manager: TransactionSigner<TAccountManager>;
  arg: SetFundingAuthorityInstructionDataArgs['arg'];
};

export function getSetFundingAuthorityInstruction<
  TAccountStakePool extends string,
  TAccountManager extends string,
  TProgramAddress extends Address = typeof SPL_STAKE_POOL_PROGRAM_ADDRESS,
>(
  input: SetFundingAuthorityInput<TAccountStakePool, TAccountManager>,
  config?: { programAddress?: TProgramAddress }
): SetFundingAuthorityInstruction<
  TProgramAddress,
  TAccountStakePool,
  TAccountManager
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? SPL_STAKE_POOL_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    stakePool: { value: input.stakePool ?? null, isWritable: true },
    manager: { value: input.manager ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.stakePool),
      getAccountMeta(accounts.manager),
    ],
    programAddress,
    data: getSetFundingAuthorityInstructionDataEncoder().encode(
      args as SetFundingAuthorityInstructionDataArgs
    ),
  } as SetFundingAuthorityInstruction<
    TProgramAddress,
    TAccountStakePool,
    TAccountManager
  >;

  return instruction;
}

export type ParsedSetFundingAuthorityInstruction<
  TProgram extends string = typeof SPL_STAKE_POOL_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    stakePool: TAccountMetas[0];
    manager: TAccountMetas[1];
  };
  data: SetFundingAuthorityInstructionData;
};

export function parseSetFundingAuthorityInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>
): ParsedSetFundingAuthorityInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 2) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      stakePool: getNextAccount(),
      manager: getNextAccount(),
    },
    data: getSetFundingAuthorityInstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
