/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getOptionDecoder,
  getOptionEncoder,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IAccountSignerMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type Option,
  type OptionOrNullable,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type TransactionSigner,
  type WritableAccount,
} from '@solana/kit';
import { SPL_STAKE_POOL_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';
import {
  getPreferredValidatorTypeDecoder,
  getPreferredValidatorTypeEncoder,
  type PreferredValidatorType,
  type PreferredValidatorTypeArgs,
} from '../types';

export const SET_PREFERRED_VALIDATOR_DISCRIMINATOR = 5;

export function getSetPreferredValidatorDiscriminatorBytes() {
  return getU8Encoder().encode(SET_PREFERRED_VALIDATOR_DISCRIMINATOR);
}

export type SetPreferredValidatorInstruction<
  TProgram extends string = typeof SPL_STAKE_POOL_PROGRAM_ADDRESS,
  TAccountStakePool extends string | IAccountMeta<string> = string,
  TAccountStaker extends string | IAccountMeta<string> = string,
  TAccountValidatorList extends string | IAccountMeta<string> = string,
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountStakePool extends string
        ? WritableAccount<TAccountStakePool>
        : TAccountStakePool,
      TAccountStaker extends string
        ? ReadonlySignerAccount<TAccountStaker> &
            IAccountSignerMeta<TAccountStaker>
        : TAccountStaker,
      TAccountValidatorList extends string
        ? ReadonlyAccount<TAccountValidatorList>
        : TAccountValidatorList,
      ...TRemainingAccounts,
    ]
  >;

export type SetPreferredValidatorInstructionData = {
  discriminator: number;
  validatorType: PreferredValidatorType;
  validatorVoteAddress: Option<Address>;
};

export type SetPreferredValidatorInstructionDataArgs = {
  validatorType: PreferredValidatorTypeArgs;
  validatorVoteAddress: OptionOrNullable<Address>;
};

export function getSetPreferredValidatorInstructionDataEncoder(): Encoder<SetPreferredValidatorInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', getU8Encoder()],
      ['validatorType', getPreferredValidatorTypeEncoder()],
      ['validatorVoteAddress', getOptionEncoder(getAddressEncoder())],
    ]),
    (value) => ({
      ...value,
      discriminator: SET_PREFERRED_VALIDATOR_DISCRIMINATOR,
    })
  );
}

export function getSetPreferredValidatorInstructionDataDecoder(): Decoder<SetPreferredValidatorInstructionData> {
  return getStructDecoder([
    ['discriminator', getU8Decoder()],
    ['validatorType', getPreferredValidatorTypeDecoder()],
    ['validatorVoteAddress', getOptionDecoder(getAddressDecoder())],
  ]);
}

export function getSetPreferredValidatorInstructionDataCodec(): Codec<
  SetPreferredValidatorInstructionDataArgs,
  SetPreferredValidatorInstructionData
> {
  return combineCodec(
    getSetPreferredValidatorInstructionDataEncoder(),
    getSetPreferredValidatorInstructionDataDecoder()
  );
}

export type SetPreferredValidatorInput<
  TAccountStakePool extends string = string,
  TAccountStaker extends string = string,
  TAccountValidatorList extends string = string,
> = {
  stakePool: Address<TAccountStakePool>;
  staker: TransactionSigner<TAccountStaker>;
  validatorList: Address<TAccountValidatorList>;
  validatorType: SetPreferredValidatorInstructionDataArgs['validatorType'];
  validatorVoteAddress: SetPreferredValidatorInstructionDataArgs['validatorVoteAddress'];
};

export function getSetPreferredValidatorInstruction<
  TAccountStakePool extends string,
  TAccountStaker extends string,
  TAccountValidatorList extends string,
  TProgramAddress extends Address = typeof SPL_STAKE_POOL_PROGRAM_ADDRESS,
>(
  input: SetPreferredValidatorInput<
    TAccountStakePool,
    TAccountStaker,
    TAccountValidatorList
  >,
  config?: { programAddress?: TProgramAddress }
): SetPreferredValidatorInstruction<
  TProgramAddress,
  TAccountStakePool,
  TAccountStaker,
  TAccountValidatorList
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? SPL_STAKE_POOL_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    stakePool: { value: input.stakePool ?? null, isWritable: true },
    staker: { value: input.staker ?? null, isWritable: false },
    validatorList: { value: input.validatorList ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.stakePool),
      getAccountMeta(accounts.staker),
      getAccountMeta(accounts.validatorList),
    ],
    programAddress,
    data: getSetPreferredValidatorInstructionDataEncoder().encode(
      args as SetPreferredValidatorInstructionDataArgs
    ),
  } as SetPreferredValidatorInstruction<
    TProgramAddress,
    TAccountStakePool,
    TAccountStaker,
    TAccountValidatorList
  >;

  return instruction;
}

export type ParsedSetPreferredValidatorInstruction<
  TProgram extends string = typeof SPL_STAKE_POOL_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    stakePool: TAccountMetas[0];
    staker: TAccountMetas[1];
    validatorList: TAccountMetas[2];
  };
  data: SetPreferredValidatorInstructionData;
};

export function parseSetPreferredValidatorInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>
): ParsedSetPreferredValidatorInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      stakePool: getNextAccount(),
      staker: getNextAccount(),
      validatorList: getNextAccount(),
    },
    data: getSetPreferredValidatorInstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
