/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IAccountSignerMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from '@solana/kit';
import { SPL_STAKE_POOL_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const SET_STAKER_DISCRIMINATOR = new Uint8Array([
  149, 203, 114, 28, 80, 138, 17, 131,
]);

export function getSetStakerDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(SET_STAKER_DISCRIMINATOR);
}

export type SetStakerInstruction<
  TProgram extends string = typeof SPL_STAKE_POOL_PROGRAM_ADDRESS,
  TAccountStakePool extends string | IAccountMeta<string> = string,
  TAccountSetStakerAuthority extends string | IAccountMeta<string> = string,
  TAccountNewStaker extends string | IAccountMeta<string> = string,
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountStakePool extends string
        ? WritableAccount<TAccountStakePool>
        : TAccountStakePool,
      TAccountSetStakerAuthority extends string
        ? ReadonlySignerAccount<TAccountSetStakerAuthority> &
            IAccountSignerMeta<TAccountSetStakerAuthority>
        : TAccountSetStakerAuthority,
      TAccountNewStaker extends string
        ? ReadonlyAccount<TAccountNewStaker>
        : TAccountNewStaker,
      ...TRemainingAccounts,
    ]
  >;

export type SetStakerInstructionData = { discriminator: ReadonlyUint8Array };

export type SetStakerInstructionDataArgs = {};

export function getSetStakerInstructionDataEncoder(): Encoder<SetStakerInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: SET_STAKER_DISCRIMINATOR })
  );
}

export function getSetStakerInstructionDataDecoder(): Decoder<SetStakerInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getSetStakerInstructionDataCodec(): Codec<
  SetStakerInstructionDataArgs,
  SetStakerInstructionData
> {
  return combineCodec(
    getSetStakerInstructionDataEncoder(),
    getSetStakerInstructionDataDecoder()
  );
}

export type SetStakerInput<
  TAccountStakePool extends string = string,
  TAccountSetStakerAuthority extends string = string,
  TAccountNewStaker extends string = string,
> = {
  stakePool: Address<TAccountStakePool>;
  setStakerAuthority: TransactionSigner<TAccountSetStakerAuthority>;
  newStaker: Address<TAccountNewStaker>;
};

export function getSetStakerInstruction<
  TAccountStakePool extends string,
  TAccountSetStakerAuthority extends string,
  TAccountNewStaker extends string,
  TProgramAddress extends Address = typeof SPL_STAKE_POOL_PROGRAM_ADDRESS,
>(
  input: SetStakerInput<
    TAccountStakePool,
    TAccountSetStakerAuthority,
    TAccountNewStaker
  >,
  config?: { programAddress?: TProgramAddress }
): SetStakerInstruction<
  TProgramAddress,
  TAccountStakePool,
  TAccountSetStakerAuthority,
  TAccountNewStaker
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? SPL_STAKE_POOL_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    stakePool: { value: input.stakePool ?? null, isWritable: true },
    setStakerAuthority: {
      value: input.setStakerAuthority ?? null,
      isWritable: false,
    },
    newStaker: { value: input.newStaker ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.stakePool),
      getAccountMeta(accounts.setStakerAuthority),
      getAccountMeta(accounts.newStaker),
    ],
    programAddress,
    data: getSetStakerInstructionDataEncoder().encode({}),
  } as SetStakerInstruction<
    TProgramAddress,
    TAccountStakePool,
    TAccountSetStakerAuthority,
    TAccountNewStaker
  >;

  return instruction;
}

export type ParsedSetStakerInstruction<
  TProgram extends string = typeof SPL_STAKE_POOL_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    stakePool: TAccountMetas[0];
    setStakerAuthority: TAccountMetas[1];
    newStaker: TAccountMetas[2];
  };
  data: SetStakerInstructionData;
};

export function parseSetStakerInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>
): ParsedSetStakerInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      stakePool: getNextAccount(),
      setStakerAuthority: getNextAccount(),
      newStaker: getNextAccount(),
    },
    data: getSetStakerInstructionDataDecoder().decode(instruction.data),
  };
}
