/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getArrayDecoder,
  getArrayEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type Account,
  type Address,
  type Codec,
  type Decoder,
  type EncodedAccount,
  type Encoder,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from '@solana/kit';
import {
  getValidatorListHeaderDecoder,
  getValidatorListHeaderEncoder,
  getValidatorStakeInfoDecoder,
  getValidatorStakeInfoEncoder,
  type ValidatorListHeader,
  type ValidatorListHeaderArgs,
  type ValidatorStakeInfo,
  type ValidatorStakeInfoArgs,
} from '../types';

export const VALIDATOR_LIST_DISCRIMINATOR = new Uint8Array([
  131, 181, 125, 127, 46, 36, 40, 167,
]);

export function getValidatorListDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    VALIDATOR_LIST_DISCRIMINATOR
  );
}

export type ValidatorList = {
  discriminator: ReadonlyUint8Array;
  header: ValidatorListHeader;
  validators: Array<ValidatorStakeInfo>;
};

export type ValidatorListArgs = {
  header: ValidatorListHeaderArgs;
  validators: Array<ValidatorStakeInfoArgs>;
};

export function getValidatorListEncoder(): Encoder<ValidatorListArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['header', getValidatorListHeaderEncoder()],
      ['validators', getArrayEncoder(getValidatorStakeInfoEncoder())],
    ]),
    (value) => ({ ...value, discriminator: VALIDATOR_LIST_DISCRIMINATOR })
  );
}

export function getValidatorListDecoder(): Decoder<ValidatorList> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['header', getValidatorListHeaderDecoder()],
    ['validators', getArrayDecoder(getValidatorStakeInfoDecoder())],
  ]);
}

export function getValidatorListCodec(): Codec<
  ValidatorListArgs,
  ValidatorList
> {
  return combineCodec(getValidatorListEncoder(), getValidatorListDecoder());
}

export function decodeValidatorList<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>
): Account<ValidatorList, TAddress>;
export function decodeValidatorList<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>
): MaybeAccount<ValidatorList, TAddress>;
export function decodeValidatorList<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>
): Account<ValidatorList, TAddress> | MaybeAccount<ValidatorList, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getValidatorListDecoder()
  );
}

export async function fetchValidatorList<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig
): Promise<Account<ValidatorList, TAddress>> {
  const maybeAccount = await fetchMaybeValidatorList(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeValidatorList<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig
): Promise<MaybeAccount<ValidatorList, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeValidatorList(maybeAccount);
}

export async function fetchAllValidatorList(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig
): Promise<Account<ValidatorList>[]> {
  const maybeAccounts = await fetchAllMaybeValidatorList(
    rpc,
    addresses,
    config
  );
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeValidatorList(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig
): Promise<MaybeAccount<ValidatorList>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeValidatorList(maybeAccount));
}
