[package]
name = "stake-pool-wrapper-core"
version = "0.1.5"
edition = "2021"
description = "Stake Pool Wrapper Core"
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/aoikurokawa/stake-pool-wrapper"

[dependencies]
