/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getEnumDecoder,
  getEnumEncoder,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/kit';

export enum AccountType {
  Uninitialized,
  StakePool,
  ValidatorList,
}

export type AccountTypeArgs = AccountType;

export function getAccountTypeEncoder(): Encoder<AccountTypeArgs> {
  return getEnumEncoder(AccountType);
}

export function getAccountTypeDecoder(): Decoder<AccountType> {
  return getEnumDecoder(AccountType);
}

export function getAccountTypeCodec(): Codec<AccountTypeArgs, AccountType> {
  return combineCodec(getAccountTypeEncoder(), getAccountTypeDecoder());
}
