/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/kit';

export type Fee = { denominator: bigint; numerator: bigint };

export type FeeArgs = {
  denominator: number | bigint;
  numerator: number | bigint;
};

export function getFeeEncoder(): Encoder<FeeArgs> {
  return getStructEncoder([
    ['denominator', getU64Encoder()],
    ['numerator', getU64Encoder()],
  ]);
}

export function getFeeDecoder(): Decoder<Fee> {
  return getStructDecoder([
    ['denominator', getU64Decoder()],
    ['numerator', getU64Decoder()],
  ]);
}

export function getFeeCodec(): Codec<FeeArgs, Fee> {
  return combineCodec(getFeeEncoder(), getFeeDecoder());
}
