/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getEnumDecoder,
  getEnumEncoder,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/kit';

export enum FundingType {
  StakeDeposit,
  SolDeposit,
  SolWithdraw,
}

export type FundingTypeArgs = FundingType;

export function getFundingTypeEncoder(): Encoder<FundingTypeArgs> {
  return getEnumEncoder(FundingType);
}

export function getFundingTypeDecoder(): Decoder<FundingType> {
  return getEnumDecoder(FundingType);
}

export function getFundingTypeCodec(): Codec<FundingTypeArgs, FundingType> {
  return combineCodec(getFundingTypeEncoder(), getFundingTypeDecoder());
}
