/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getU8Decoder,
  getU8Encoder,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/kit';

export type PodStakeStatus = number;

export type PodStakeStatusArgs = PodStakeStatus;

export function getPodStakeStatusEncoder(): Encoder<PodStakeStatusArgs> {
  return getU8Encoder();
}

export function getPodStakeStatusDecoder(): Decoder<PodStakeStatus> {
  return getU8Decoder();
}

export function getPodStakeStatusCodec(): Codec<
  PodStakeStatusArgs,
  PodStakeStatus
> {
  return combineCodec(getPodStakeStatusEncoder(), getPodStakeStatusDecoder());
}
