/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getEnumDecoder,
  getEnumEncoder,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/kit';

export enum PreferredValidatorType {
  Deposit,
  Withdraw,
}

export type PreferredValidatorTypeArgs = PreferredValidatorType;

export function getPreferredValidatorTypeEncoder(): Encoder<PreferredValidatorTypeArgs> {
  return getEnumEncoder(PreferredValidatorType);
}

export function getPreferredValidatorTypeDecoder(): Decoder<PreferredValidatorType> {
  return getEnumDecoder(PreferredValidatorType);
}

export function getPreferredValidatorTypeCodec(): Codec<
  PreferredValidatorTypeArgs,
  PreferredValidatorType
> {
  return combineCodec(
    getPreferredValidatorTypeEncoder(),
    getPreferredValidatorTypeDecoder()
  );
}
