/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getEnumDecoder,
  getEnumEncoder,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/kit';

export enum StakeWithdrawSource {
  Active,
  Transient,
  ValidatorRemoval,
}

export type StakeWithdrawSourceArgs = StakeWithdrawSource;

export function getStakeWithdrawSourceEncoder(): Encoder<StakeWithdrawSourceArgs> {
  return getEnumEncoder(StakeWithdrawSource);
}

export function getStakeWithdrawSourceDecoder(): Decoder<StakeWithdrawSource> {
  return getEnumDecoder(StakeWithdrawSource);
}

export function getStakeWithdrawSourceCodec(): Codec<
  StakeWithdrawSourceArgs,
  StakeWithdrawSource
> {
  return combineCodec(
    getStakeWithdrawSourceEncoder(),
    getStakeWithdrawSourceDecoder()
  );
}
