/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getEnumDecoder,
  getEnumEncoder,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/kit';

export enum StakeStatus {
  Active,
  DeactivatingTransient,
  ReadyForRemoval,
}

export type StakeStatusArgs = StakeStatus;

export function getStakeStatusEncoder(): Encoder<StakeStatusArgs> {
  return getEnumEncoder(StakeStatus);
}

export function getStakeStatusDecoder(): Decoder<StakeStatus> {
  return getEnumDecoder(StakeStatus);
}

export function getStakeStatusCodec(): Codec<StakeStatusArgs, StakeStatus> {
  return combineCodec(getStakeStatusEncoder(), getStakeStatusDecoder());
}
