/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/kit';
import {
  getAccountTypeDecoder,
  getAccountTypeEncoder,
  type AccountType,
  type AccountTypeArgs,
} from '.';

export type ValidatorListHeader = {
  accountType: AccountType;
  maxValidators: number;
};

export type ValidatorListHeaderArgs = {
  accountType: AccountTypeArgs;
  maxValidators: number;
};

export function getValidatorListHeaderEncoder(): Encoder<ValidatorListHeaderArgs> {
  return getStructEncoder([
    ['accountType', getAccountTypeEncoder()],
    ['maxValidators', getU32Encoder()],
  ]);
}

export function getValidatorListHeaderDecoder(): Decoder<ValidatorListHeader> {
  return getStructDecoder([
    ['accountType', getAccountTypeDecoder()],
    ['maxValidators', getU32Decoder()],
  ]);
}

export function getValidatorListHeaderCodec(): Codec<
  ValidatorListHeaderArgs,
  ValidatorListHeader
> {
  return combineCodec(
    getValidatorListHeaderEncoder(),
    getValidatorListHeaderDecoder()
  );
}
