[package]
name = "stake-pool-wrapper-sdk"
version = "0.1.2"
edition = "2021"
description = "Stake Pool Wrapper SDK"
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/aoikurokawa/stake-pool-wrapper"

[dependencies]
borsh = { workspace = true }
shank = { workspace = true }
