[package]
name = "stake-pool-wrapper-sdk"
version = "0.1.0"
edition = "2021"
description = ""
license = "Apache-2.0"
readme = "README.md"

[dependencies]
borsh = { workspace = true }
shank = { workspace = true }
